### PR TITLE
two new algorithms added, fair oversampling and fair downsampling

### PR DESCRIPTION
**Pull request by ckalousi**

### CODE REVIEW

**Review by koji8y — CHANGES_REQUESTED** [review]
It seems hard for users to reach the code for the new algorithms.
- README.md should have the links to the ipynb files (`guide and examples.ipynb` and `Fair Oversampling guide.ipynb`) for the guidance of the algorithms. Could you add the links?
- Directory names `fd` and `fo` in `src` are too short to grasp the meanings. Could you change the names, e.g., `fair_downsampling`?

**Comment by ckalousi** [comment]
@koji8y 

Thank you for your comments and suggested usability improvements.  I have changed the names of the folders and I added the links of the tutorials in the README.md file.

**Comment by koji8y** [comment]
@ckalousi 
Thank you for your prompt modification.

It looks good to me except for the tiny matter that the links to the ipynb files are expressed using absolute paths, which can be relative in Markdown for robustness against root URL changes. You can see examples of that at the bottom of README.md, in sections "Support" or "License".

In concrete, the first link can be changed from `https://github.com/intersectional-fairness/isf/tree/main/src/fair_oversampling/fair_oversampling_tutorial.ipynb` to `[Tutorial](src/fair_oversampling/fair_oversampling_tutorial.ipynb)`. (The link label `Tutorial` is just an example.)

Could you change these expressions?

**Comment by ckalousi** [comment]
thank you @koji8y for the catch, I have made the requested changes

**Pull request merged**
